on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: Ubuntu-latest

    steps:
      - name: "list all files"
        run: ls
      
      - uses : actions/checkout@v3
      - name: "list all files after"
        run: ls 


